name: Push builds

on:
  push:
    branches:
      - main

jobs:
  build-web:
    uses: Srynetix/godot-github-workflows/.github/workflows/build-game-4.0.2.yml@main
    with:
      platform: Web
      name: unknown-car-game
      output_name: index.html