name: Push builds

on:
  push:
    branches:
      - main

jobs:
  build-web:
    uses: Srynetix/godot-github-workflows/.github/workflows/build-game-3.5.1.yml@main
    with:
      platform: HTML5
      name: unknown-car-game
      output_name: index.html
  build-linux:
    uses: Srynetix/godot-github-workflows/.github/workflows/build-game-3.5.1.yml@main
    with:
      platform: Android
      name: unknown-car-game
      output_name: UnknownCarGame.apk
      debug: true